// <auto-generated />
using System;
using CryptoExchange.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoExchange.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251004115140_JustATest")]
    partial class JustATest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoExchange.Models.CryptoCurrency", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("CryptoCurrencies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Самая известная криптовалюта",
                            Name = "Bitcoin",
                            ShortName = "BTC",
                            Symbol = "₿"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Смарт-контракты",
                            Name = "Ethereum",
                            ShortName = "ETH",
                            Symbol = "Ξ"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Стейблкоин к доллару",
                            Name = "Tether",
                            ShortName = "USDT",
                            Symbol = "$"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Binance Coin",
                            Name = "BNB",
                            ShortName = "BNB",
                            Symbol = "ⓑ"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Быстрый блокчейн",
                            Name = "Solana",
                            ShortName = "SOL",
                            Symbol = "◎"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Экологичная криптовалюта",
                            Name = "Cardano",
                            ShortName = "ADA",
                            Symbol = "₳"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Мгновенные платежи",
                            Name = "XRP",
                            ShortName = "XRP",
                            Symbol = "✕"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Мем-валюта",
                            Name = "Dogecoin",
                            ShortName = "DOGE",
                            Symbol = "Ð"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Мульти-блокчейн",
                            Name = "Polkadot",
                            ShortName = "DOT",
                            Symbol = "●"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Серебро к золоту BTC",
                            Name = "Litecoin",
                            ShortName = "LTC",
                            Symbol = "Ł"
                        },
                        new
                        {
                            ID = 11,
                            Description = "Оракулы для блокчейна",
                            Name = "Chainlink",
                            ShortName = "LINK",
                            Symbol = "🔗"
                        },
                        new
                        {
                            ID = 12,
                            Description = "Высокая производительность",
                            Name = "Avalanche",
                            ShortName = "AVAX",
                            Symbol = "🗻"
                        },
                        new
                        {
                            ID = 13,
                            Description = "Дешевые международные переводы",
                            Name = "Stellar",
                            ShortName = "XLM",
                            Symbol = "*"
                        },
                        new
                        {
                            ID = 14,
                            Description = "Анонимные транзакции",
                            Name = "Monero",
                            ShortName = "XMR",
                            Symbol = "ɱ"
                        },
                        new
                        {
                            ID = 15,
                            Description = "Контент-платформа",
                            Name = "Tron",
                            ShortName = "TRX",
                            Symbol = "T"
                        },
                        new
                        {
                            ID = 16,
                            Description = "Смарт-контракты с высокой скоростью",
                            Name = "EOS",
                            ShortName = "EOS",
                            Symbol = "ε"
                        },
                        new
                        {
                            ID = 17,
                            Description = "Цепочка поставок",
                            Name = "VeChain",
                            ShortName = "VET",
                            Symbol = "V"
                        },
                        new
                        {
                            ID = 18,
                            Description = "Децентрализованные финансы",
                            Name = "Aave",
                            ShortName = "AAVE",
                            Symbol = "Æ"
                        },
                        new
                        {
                            ID = 19,
                            Description = "Взаимодействие блокчейнов",
                            Name = "Cosmos",
                            ShortName = "ATOM",
                            Symbol = "⚛"
                        },
                        new
                        {
                            ID = 20,
                            Description = "Децентрализованная биржа",
                            Name = "Uniswap",
                            ShortName = "UNI",
                            Symbol = "🦄"
                        },
                        new
                        {
                            ID = 21,
                            Description = "Стейблкоин Dai",
                            Name = "Maker",
                            ShortName = "MKR",
                            Symbol = "M"
                        },
                        new
                        {
                            ID = 22,
                            Description = "Масштабируемость и безопасность",
                            Name = "Algorand",
                            ShortName = "ALGO",
                            Symbol = "A"
                        },
                        new
                        {
                            ID = 23,
                            Description = "Конфиденциальность",
                            Name = "Zcash",
                            ShortName = "ZEC",
                            Symbol = "ⓩ"
                        },
                        new
                        {
                            ID = 24,
                            Description = "Автоматическое обновление протокола",
                            Name = "Tezos",
                            ShortName = "XTZ",
                            Symbol = "ꜩ"
                        },
                        new
                        {
                            ID = 25,
                            Description = "Китайский Ethereum",
                            Name = "NEO",
                            ShortName = "NEO",
                            Symbol = "🅝"
                        });
                });

            modelBuilder.Entity("CryptoExchange.Models.MarketPriceCache", b =>
                {
                    b.Property<int>("CurrencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CurrencyID"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PriceInUSDT")
                        .HasColumnType("double precision");

                    b.HasKey("CurrencyID");

                    b.ToTable("MarketPriceCaches");
                });

            modelBuilder.Entity("CryptoExchange.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrencyID")
                        .HasColumnType("integer");

                    b.Property<double>("ExchangeRate")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsSellOrder")
                        .HasColumnType("boolean");

                    b.Property<int>("WalletID")
                        .HasColumnType("integer");

                    b.Property<bool>("isFilled")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("WalletID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CryptoExchange.Models.Trade", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("BuyOrderID")
                        .HasColumnType("integer");

                    b.Property<int>("SellOrderID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("BuyOrderID");

                    b.HasIndex("SellOrderID");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("CryptoExchange.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CryptoExchange.Models.Wallet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<int>("CurrencyID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("UserID");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("CryptoExchange.Models.Order", b =>
                {
                    b.HasOne("CryptoExchange.Models.CryptoCurrency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoExchange.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoExchange.Models.Trade", b =>
                {
                    b.HasOne("CryptoExchange.Models.Order", "BuyOrder")
                        .WithMany()
                        .HasForeignKey("BuyOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoExchange.Models.Order", "SellOrder")
                        .WithMany()
                        .HasForeignKey("SellOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyOrder");

                    b.Navigation("SellOrder");
                });

            modelBuilder.Entity("CryptoExchange.Models.Wallet", b =>
                {
                    b.HasOne("CryptoExchange.Models.CryptoCurrency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoExchange.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
